---
title: "Milestone 5"
author: "Ali Crump"
date: "10/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About


The National Hockey League (NHL) recently published the complete digitization of their statistical records, dating back 100 years to the first season in 1917-1918. This data includes team statistics and player statistics as well as visualization and filtering tools at [www.nhl.com]( http://www.nhl.com/stats/). The page includes more than 15 million player and game data points, with those from 1917 to 1987 previously unavailable. The data points range from more typical ice hockey statistics such as goals, assists, and points to penalty minutes, shot percentage, and time on ice. 

The data is not available for download on their website, so I had to extract the data from the website using webscraping software from [webscraper.io](https://webscraper.io/). The website includes tutorials for how to navigate different website layouts, so I essentially followed those instructions and solved issues with trial and error. This software is an extension for Google Chrome and allows you to select the data on the website you’re interested in, and then it navigates multiple pages of the site until it has extracted all of the data. Once the data has been extracted, I am able to download it as a csv file which R is able to understand. One complication I faced was the sheer amount of data; my computer was not able to extract it all at once. I had to section the data by year, into 25 year increments so that my computer could extract the data in a reasonable amount of time.

I love the idea of using analytics in sports because it ramps up the competition factor; each team is trying to get an advantage over the others in any way that they can, and turning to analytics can allow you to view the data in a new and potentially illuminating way. Analytics is increasingly being applied to sports; teams in the MLB have large sabermetrics and statistics departments, for example. I’m on the women’s lacrosse team at Harvard and we even have a mathematician who evaluates our practices! 

I decided to choose NHL data for my project because I have grown up watching the Philadelphia Flyers and attending games with my family. I really wanted to apply this type of analysis to a team I’ve followed my whole life to perhaps see how their goals, power plays, save percentage, and more have had an effect (if any) on their record and standings over the years.

