---
title: "Final project"
author: "Ali Crump"
date: "10/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Milestone4

My plan for my project was to webscrape it, but even after watching webscraper.io tutorials numerous times I couldn't successfully export the data. I downloaded the webscraper.io extension for Google Chrome and I first made the sitemap url this page [www.nhl.com](http://www.nhl.com/stats/player?reportType=season&seasonFrom=19171918&seasonTo=20192020&gameType=2&filter=gamesPlayed,gte,1&sort=points,goals,assists). I then made an element selector and highlighted the whole table. Within that element selector I made all of the text selectors: name, team, goals, etc. I wanted to make sure I got the single page to load before transitioning to the click element selector because there are nearly 50 pages of data. I also explored other selector types such as table, but was unable to get that to work. I might try another webscraper software and see if that might work.  
If I had gotten the webscraper to work, I would load the data in as a csv file and clean it using clean_names() and the janitor package. I would then explore it a bit using View(), glimpse(), and summary(). I was hoping to create a visual that showed the Philadelphia Flyers season vs points, so I would have filtered for the flyers then used ggplot and geom line or geom scatter perhaps. I'm curious to see how the team has improved or not improved throughout the years.    

I discussed the issues I've had and my current plan with Preceptor and he says that submitting what I have is fine. 